num_epoch:
  phase_1: 40
  phase_2: 55
  phase_3: 55
  phase_4: 50
  phase_5: 55
  phase_6: 50
  phase_7: 50
  phase_8: 50
  phase_9: 50
  phase_10: 70

step_size:
  phase_1: 16
  phase_2: 30
  phase_3: 34
  phase_4: 28
  phase_5: 32
  phase_6: 23
  phase_7: 24
  phase_8: 21
  phase_9: 25
  phase_10: 45